### PR TITLE
Swagger core 2.0.0

### PR DESCRIPTION
**Pull request by pjfanning**
Relates to https://github.com/swagger-api/swagger-scala-module/issues/49
* Uses changes in swagger-core 2.0.4
* The only thing that is broken compared to v1.0.4 is scala enum support

### CODE REVIEW

**Comment by pjfanning** [comment]
I've published this branch as a snapshot to https://oss.sonatype.org/content/repositories/staging/

`"com.github.swagger-akka-http" %% "swagger-scala-module" % "2.0.0-SNAPSHOT"`

**Comment by cellux-git** [comment]
An issue I noticed with this one: the optional values in scala case classes are documented as objects with 2 fields: "empty", "defined"

**Comment by pjfanning** [comment]
@zsoltherpai could you be hitting https://github.com/swagger-api/swagger-scala-module/issues/55 ?

**Comment by cellux-git** [comment]
> @zsoltherpai could you be hitting #55 ?

Sorry that was my mistake, the converter has not been correctly registered.
  
Another issue I noticed: Option[AnyRef] works fine now but having problems with Option[AnyVal]

For example Option[Int] shows up as 
`{
   "type" : "object"
 }`

Annotating the field as a temporary workaround didn't work (still type: object)
`@Schema(`type`=` "integer")`

**Comment by pjfanning** [comment]
@zsoltherpai I've reproduced the issue where `@Parameter` and `@Schema` annotations don't seem to seem to allow overrides of the param type - most of the code that is used in the model generation comes from https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jaxrs2 - so might be best to report that issue there

One workaround is to use Option[BigInt] instead of Option[Int]. The type erasure issue only seems to affect primitives like Int, Boolean etc.

**Comment by pjfanning** [comment]
@zsoltherpai I fixed the issue with the annotations being ignored in my fork of [swagger-scala-module](https://github.com/swagger-akka-http/swagger-scala-module). There is a sample that demonstrates the fix - https://github.com/pjfanning/swagger-akka-http-sample

**Comment by cellux-git** [comment]
Thanks, it works better now. Bumped into some new issues.
Option[Array[String]]  - in an attempt to make the field non-required -
fails with a nullpointer exception in the jackson model resolver. Then I
tried plain Array[Integer]  annotated with @Schema(required = false) . This
doesn't do much. However @Schema(name = "whatever") does make the field
non-required.

**Comment by cellux-git** [comment]
Setting any property of @Schema to a non-default value does the trick (eg
defaultValue).

**Comment by reppners** [comment]
Would this PR enable enum support? Is there anything I can do to support the effort?

**Comment by pjfanning** [comment]
https://github.com/pjfanning/swagger-akka-http-sample has an example of how to handle an enum with swagger-2 - not ideal but I haven't been able to fix the automatic handling of enums

**Comment by gaeljw** [comment]
Wow great work, how can we make the project move forward especially with this PR?

**Comment by pjfanning** [comment]
I have a fork that supports swagger 2 / OpenAPI 3 - https://github.com/swagger-akka-http/swagger-scala-module

**Comment by gaeljw** [comment]
@pjfanning Do you use the swagger-scala-module only? I started having a look at using it in swagger-play but there's a significant amount of changes, not sure it's worth the effort considering that other alternatives such as Tapir already provides OAS 3.0 support (in a totally different way than swagger-play obviously).

**Comment by pjfanning** [comment]
@gaeljw I'm keeping alive swagger-scala-module (in a fork) because it is used in some existing libs that can use the updated code. It is good to see alternatives because swagger-scala-module is based on Java reflection and there are issues with type erasure that can be avoided with alternative approaches.

I just gave up on this PR because it is time consuming to keep it updated but with little chance of it being merged.

**Pull request closed without merging**
